### ISSUE TITLE
`Don't know what to do with 'src/util.hpp`: issues on CUDA 11.1 and above

### ISSUE THREAD

**Issue by multimeric** [CMU-SAFARI/Scrooge#2]
I believe there is a bug in the makefile, because the specific header files are being passed to `nvcc` when they shouldn't be. As a consequence you get this error:
```
nvcc fatal   : Don't know what to do with 'src/util.hpp'
make: *** [library_example_linux] Error 1
```

I think the bug is here:
https://github.com/CMU-SAFARI/Scrooge/blob/f9c6ea1b5efba361e411aedb680433902bf284c4/Makefile#L38

I suppose that in earlier versions of CUDA, `nvcc` ignored files that it didn't know how to compile, but this has become an error in CUDA 11.1 and above.

**Comment by claus-h-g** [comment]
Using Cuda 11.7 on xUbuntu 18.04.

I did modify line 14 form:
"HEADERS := bitvector_test.hpp bitvector.hpp cuda_list.hpp cuda_util.hpp filesystem.hpp genasm_cpu.hpp genasm_gpu.hpp util.hpp"

to 
"HEADERS :="

everything without quotes.
and compilation succeeded.
Hope this helps

**Comment by joellindegger** [comment]
Hi both

Thanks for looking into this issue.
a4586ff499884ff84c3268c767dd272037710df7 addresses it.

Best,
Joel
