### ISSUE TITLE
DATASETS.md - url not found

### ISSUE THREAD

**Issue by claus-h-g** [CMU-SAFARI/Scrooge#3]
Hello,
Many thanks for providing Scrooge.
I would like to use it in my own Datasets but the term  DATASETS.md points to "https://github.com/CMU-SAFARI/Scrooge/blob/main/DATASETS.md". This promts to a page with a 404 error "This is not the web page you are looking for". 
Could you please provide a description how to use my own datasets?
Many thanks

**Comment by joellindegger** [comment]
Hi
Thanks for pointing this out. I just added the missing file.

To use a custom dataset you can prepare yours analogously to the ones in DATASETS.md
To use Scrooge's evaluation scripts you need to supply a .fasta file with the reference genome, a .fastq file with the reads, and a .paf or .maf file with the candidate locations in the reference genome for each read.

If your custom dataset looks different (e.g., you only have a file of string pairs), it's easiest to write your own wrapper around Scrooge's library interface, as shown in [library_example.cu](https://github.com/CMU-SAFARI/Scrooge/blob/main/src/library_example.cu).

Best,
Joel
