### ISSUE TITLE
Makefile missing

### ISSUE THREAD

**Issue by rchikhi** [CMU-SAFARI/Scrooge#4]
Hi, I wanted to test Scrooge, but it seems the repository is missing at least its makefile:

```
git clone https://github.com/CMU-SAFARI/Scrooge && cd Scrooge
make tests_linux
```
returns
```make: *** No rule to make target 'tests_linux'.  Stop.```

**Comment by joellindegger** [comment]
The Makefile got lost in the latest update, thanks for reporting the issue!
f3e4f799060a571248805628f9ed40ffd0d12421 should fix it.

Best,
Joel
